### ISSUE TITLE
"Default" text in slot

### ISSUE THREAD

**Issue by ndovnar** [shubhadip/vuejs3-datepicker#37] opened 2022-05-17 12:41 UTC
Greetings, thanks for your efforts!
I found a minor issue, it looks like there's forgotten text in the slot.
[here](https://github.com/shubhadip/vuejs3-datepicker/blob/master/src/components/datepicker/DateInput.vue#L68)

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/11501912/168812780-518b616d-daeb-437f-8a25-52c46c0559cd.png">

**Comment by shubhadip** [comment] 2022-05-20 12:59
the issue is resolved in latest release

**Comment by ndovnar** [comment] 2022-05-20 14:04
@shubhadip thanks a lot!

**Closed** 2022-05-20 14:04 UTC
